import {
  BarChart3,
  Building,
  Calendar,
  DollarSign,
  FileText,
  Gift,
  Headphones,
  Heart,
  Home,
  MessageSquare,
  Settings,
  UserCheck,
  Users,
} from 'lucide-react';

export const ChurchNavigation = [
  { name: 'Dashboard', href: '/church', icon: Home, badge: null },
  { name: 'Users', href: '/church/users', icon: Users, badge: null },
  {
    name: 'Branches',
    href: '/church/branches',
    icon: Building,
    badge: null,
  },
  {
    name: 'Departments',
    href: '/church/departments',
    icon: Users,
    badge: null,
  },
  { name: 'Small Groups', href: '/church/groups', icon: Users, badge: null },
  {
    name: 'Attendance',
    href: '/church/attendance',
    icon: UserCheck,
    badge: 'New',
  },
  { name: 'Events', href: '/church/events', icon: Calendar, badge: null },
  {
    name: 'Finance',
    href: '/church/finance',
    icon: DollarSign,
    badge: null,
  },
  {
    name: 'Contributions',
    href: '/church/contributions',
    icon: Gift,
    badge: null,
  },
  { name: 'Assets', href: '/church/assets', icon: Building, badge: null },
  {
    name: 'Communication',
    href: '/church/communication',
    icon: MessageSquare,
    badge: '3',
  },
  {
    name: 'Discipleship',
    href: '/church/discipleship',
    icon: Heart,
    badge: null,
  },
  {
    name: 'Volunteers',
    href: '/church/volunteers',
    icon: UserCheck,
    badge: null,
  },
  {
    name: 'Prayer Requests',
    href: '/church/prayer',
    icon: Headphones,
    badge: '5',
  },
  { name: 'Content', href: '/church/content', icon: FileText, badge: null },
  { name: 'Reports', href: '/church/reports', icon: BarChart3, badge: null },
  {
    name: 'Settings',
    href: '/church/settings',
    icon: Settings,
    badge: null,
  },
] as const;
